### ISSUE TITLE
missing pocoxml.dll in windows packaged app

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1044]

**Comment by IndrekV** [comment]
Strangely this only happens when upgrading from version 145 to something like 163. If I uninstall the old version and then download the new and install it. No missing DLL error occur. Might be something to do with the fact that the application is opened when installer is started and some files might be in use.

**Comment by IndrekV** [comment]
Might also be an Advancedinstaller issue http://david-homer.blogspot.com/2012/07/files-missing-after-upgrade-with.html

**Comment by tanel** [comment]
The dll is included with AIP file, so it does look like an Advanced Installer issue. Then it will be fixed with switching to a new installer (exe).
