### ISSUE TITLE
Linux app keeps resizing the window after user finishes editing a time entry

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1109]

**Comment by IndrekV** [comment]
is connected to `getSizeHint` that is in the timeentrycellwidget.cpp.  Set SizeHint acts a littlebit as setMinimumSize. Basically setSizeHint changes both width and height. We only actually need height changing to make entries with header taller.

Might be fixed with eda92db8895c0e61be0e5abd3001c17563081c51  Needs to be double checked.
