### ISSUE TITLE
Minimum horizontal width is rather large; reduce 2x

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1113]

**Comment by jgindin** [comment]
Just to add some additional feedback on this:

When the window is too narrow (which, by the way, it is the first time I start the app) the time I've spent on my tasks is cut off. Instead of showing, e.g., "15:36 min" or "01:00:01", all I see is "15:3" and "01:0" (where even the last digit there is only partially showing).

**Comment by tanel** [comment]
428 pixels minimum width looks ok to me
