### ISSUE TITLE
Enable multiple user accounts

### ISSUE THREAD

**Issue by benfurfie** [toggl/toggldesktop#1247]
I've been using TogglDesktop for my own projects for a while now and I'm loving it. Thank you to everyone for making this happen.

However, in the last week I have begun working with another agency that uses Toggl to track time. My only real request is that it would be great to easily switch between different toggl accounts/remain logged into several accounts at same time, rather than having to log in and out.

I have had a good look through the Mac application, however I have not been able find such functionality. This leads me to believe that the functionality is not present in the software at this moment in time.

It's not a make or break issue. At the moment, I am using the web application for my clients work. However, the desktop application is so good it would be great to be able to use it for tracking time for both my own work and my client's.

**Comment by IndrekV** [comment]
One toggl account can have multiple workspaces connected to it. Meaning that your personal account can be invited to the other agency workspace and this way you can track time to your account and to the agency-s account when ever needed.

If the issue is that you have the need to track multiple timers at the same time then this is not possible form inside one application and one toggl account. One account can run only one timer at one moment. For running multiple timers you would have to use two different applications (desktop and web for example) and two different accounts. I hope this clears things up.
