### ISSUE TITLE
Non-admins can create Projects via Desktop App even when WS settings are admin only

### ISSUE THREAD

**Issue by epagnini** [toggl/toggldesktop#1332]
Windows App - 156408 - deleted projects also do not get removed from app

**Comment by amulware** [comment]
Not sure if this is still relevant. Will investigate.

**Comment by amulware** [comment]
In my test, this was not possible. When trying to create a project in a workspace that I was not allowed to create projects for, the library returned the error "project name already exists".

Interestingly, it DID change the time entry to be part of that workspace, and thereby now hides the 'add project' button for it.

I am not sure what the exact behaviour should be here, but this issue seems resolved.
