### ISSUE TITLE
Timer broken in Hi-dpi mode

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1379]

**Comment by amulware** [comment]
See #1382 for a bunch of screenshots, showing the problem also affecting edit and preference forms.

**Comment by amulware** [comment]
Note: Most of these issues will be fixed by the migration of edit view, timer, and preferences to WPF, see #1042, #1392, and #1374.

Then, still left to look at (and fix if needed) are the about window, the main (and preferences?) window title and icon, and resize handles.

Also, it may be worth investigating the blurry issue: #1232 (only reported once so far).

**Comment by amulware** [comment]
Closed as wpf timer and preferences have been merged into master.
