### ISSUE TITLE
Hold only a certain number of latest builds 

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1454]
Let's keep:
 - last 5 stable builds
 - last 5 beta builds
 - and 20 of dev builds. 

Others can be removed.

**Comment by tanel** [comment]
we know currently only about the current and previous stable/beta/dev build. so there's no easy way to do this. we should probably just stop uploading to Toggl download server (assuming this issue is about Toggl download server) and drop the whole build archive once its done and all the updates point to Github.
