### ISSUE TITLE
Enter should also save the field 

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1468]
Currently only field blur triggers the change.

**Comment by amulware** [comment]
For the three time boxes this will result in a double save. Once when the user hits enter, and secondly when the field is unfocused. The second save is necessary so that the library gets the chance to update the time field with the correct display format.

This also means that the library has to accept non-changes in this case. I believe it does, so this is most likely no problem. Just making sure we are aware of possible future complications.

**Comment by tanel** [comment]
double save should be no problem; also non-changes

**Comment by amulware** [comment]
Very good!

Since this really only applies to the time end description fields, it should be fairly trivial.

I'll get around to it soon.™
