### ISSUE TITLE
Crash when sync with site

### ISSUE THREAD

**Issue by Paul-N** [toggl/toggldesktop#1520]
An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll

Additional information: The given key was not present in the dictionary.

How to repro: Open toggle in browser -> Create a new workspace -> create a project in this workspace -> start a new task in this project. Then go to already running toggle app and click Syncronyze option in menu -> Crash

Sorry, Visual Studio doesn't show any stack trace for this Exception

**Comment by amulware** [comment]
Thanks for reporting this and for including the steps to reproduce!

We'll look into this soon.

**Comment by amulware** [comment]
I was able to reproduce the problem (just creating a new client in the new workspace was enough for me, crashed within 2 seconds, because websockets).

It seems that the UI is not notified of the new workspace, which results in a crash when it tries to categorize the new client/project by workspace.

@tanel: we may want to look into this together.

**Comment by amulware** [comment]
The options that I see are:

1. making sure that the library always updates workspaces before it updates clients/projects
2. catch the exception in the ui, and try again, once the workspace is updated
3. Remove the dependencies between the different lists

I think 3 is the nicest option (since it comes with the added benefit of removing the dependencies), and should be pretty easy to do. All that is needed for that is:

- add workspace name to client auto-completion item view (TogglGenericView)
- add workspace name to project auto-completion item view (TogglAutocompleteView)

and if you like to make me happy (and my code simpler and faster):

- add client id to project auto-completion item view (TogglAutocompleteView)

But that is optional for fixing the bug.

Let me know what you think, @tanel.
I am also open to the other options if you think one of them is better.

**Comment by tanel** [comment]
will implement option 3, thx
