### ISSUE TITLE
Shortcuts reset on every update

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1528]
User reported that with each update the shortcuts seem to be reset. Reported on Windows 8.1
More info: 172661

**Comment by egoroof** [comment]
I've updated from stable to beta channel and got this issue too. Win8.1 too

**Comment by amulware** [comment]
The problem seems to be that every new version (by version number) uses a different settings file.

For example, for me the current version uses:
```
C:\Users\amulware\AppData\Local\Toggl\TogglDesktop.exe_Url_5ntuzjx0y03kd3t2vr02r42tx2cq1n2a\7.2.348.0\user.config
```

And there are other folders for the different version numbers, each containing their own config file.

This causes windows-specific settings (window state and global shortcuts) to not be carried over to new versions.

**Comment by amulware** [comment]
Moved all settings to database. Currently maximised/minimised state does not seem to be saved properly and always returns `true`. Once that is figured out, this can be closed.

**Comment by amulware** [comment]
Confirmed to work now.
