### ISSUE TITLE
Don't allow editing install directory

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1759]
As we have built the app to be installed on the user directory there is no reason to allow the users to choose the location as no other location works. We just show the location of the installation and disable editing.

**Comment by cdecron** [comment]
Hello,

My AppData folder location is not the classic one, since I have a tiny SSD and I moved it. However, Toggl installation wizard want to install it in my old AppData folder (which doesn't exist anymore). I'd like to change installation folder location (at least to my new AppData folder, if it's not in "Program Files") but I can't. Can this problem be fixed?

Thanks a lot

**Comment by IndrekV** [comment]
The installer gets the user location from the param called `$LOCALAPPDATA` It is something that is added to the Windows registry after the user account is created. You should update the value in registry to make it work properly.

**Comment by cdecron** [comment]
Sorry, indeed you're right. My computer probably needed a reboot before the new AppData var is taken in account.
Thank you!
