### ISSUE TITLE
Project name already exists

### ISSUE THREAD

**Issue by HugoHeneault** [toggl/toggldesktop#1762]
Hello, 

I'm facing an issue on 7.3.199 (win) while creating a new client & project at the same time:

For example, I already have a client `A` with a project named `dev`. If I try to create a new client `B` and a new project `dev` at the same time, I've got the error `Project name already exists`.

The only way I found to do what I want is to use the wep app... 

Thanks!

**Comment by HugoHeneault** [comment]
Update: The client `B` is created, but not the project.

**Comment by IndrekV** [comment]
in osx the client saving and project saving are with different actions. Right after the client save the correct client id is set in the edit form. The client save action return client GUID.

**Comment by amulware** [comment]
This is the same on Windows.

**Comment by amulware** [comment]
My best guess is that the library does not check for duplicates correctly. We had several issues like that in the past.

**Comment by IndrekV** [comment]
Just tested on osx and windows. The issue is windows specific. On Osx the client is created with one click and after that when you close the edit view the project is created with the newly created client id. In windows the client save and project save are with the same action and it seems that something is mixed up somewhere in this process.

**Comment by amulware** [comment]
When testing, I get the same behaviour as described by Hugo - with one difference: both the client and the project are created.
I also get the exact same behaviour when creating client and project separately (client can be created by hitting ENTER in the client name box).

However, it still gives the 'duplicate project name' error message. And a second later it correctly sets the new project+client for the time entry.

I am at this point very much convinced that the fault is not in the ui code, but in the library.

In other words: I cannot find anything that is mixed up with the creation of clients and projects in the win-ui. It saves the returned GUID of the created client, and gives it to the library for the created project, and the library creates both client and project just fine.

I remember discussing this a few months ago, and am convinced that the win-ui implementation is correct. I think we even made changes so that the project can be created just from the GUID. If it could not be, all sorts of things would be messed up if the user is clicking around too fast, or if they do not have an internet connection, since only the backend can assign client-ids.

**Comment by amulware** [comment]
Turns out the error was with an event from the library that was called during adding the project, which caused a second submission of the project-add call, which then failed. Put in a check against this case.

**Comment by HugoHeneault** [comment]
Hi there. 

I'm facing this issue again. 
When I create a new project/client at the same time, the client is added (I can see it on the webapp -- not in the win app), but the project isn't, and I still got the error message...

**Comment by amulware** [comment]
Hey @HugoHeneault,

Can you make sure that you have the newest version of the app? (7.3.252)
You can check the version in the about window.

If the error still occurs with that version, can you give us exact steps to reproduce it?

**Comment by HugoHeneault** [comment]
Yeah, it's that version. 

1. Writing "Test" in "What are you doing" field.
2. Starting the task
3. Opening task details
4. Clicking "Add new project"
5. Then "Add new client"
6. Writing "Client A" in "client"
7. Then "Graphismes" in "project"
8. Clicking on "save" 

After trying ~10 times, I figured out the bug occurs only when typing "Graphismes" in the project name. Weird.

Any ideas?

**Comment by amulware** [comment]
So, the client shows up only in the webapp, but not in the desktop app?
Does the project show up in either place, or is it not created at all?

**Comment by HugoHeneault** [comment]
The client doesn't show in the desktop app, appears in the webapp.
The project doesn't seems to be created.

**Comment by amulware** [comment]
Seems like there may be another bug hidden somewhere. Opening for further investigation
