### ISSUE TITLE
Linux documentation link broken

### ISSUE THREAD

**Issue by bmreilly** [toggl/toggldesktop#1920]
Hello,
I was attempting to get some info on how to run toggldesktop by browsing the docs.  There is a line at the bottom of the docs: 

> More detailed description is available at Linux UI Documentation

However the link `Linux UI Documentation` is broken

**Comment by IndrekV** [comment]
The general guide to running the desktop app is in the Readme.md https://github.com/toggl/toggldesktop/blob/master/README.md#linux

Also there is this wiki article if you want to build app from source.
https://github.com/toggl/toggldesktop/wiki/Building-Toggl-Desktop-from-source-for-usage-with-live-servers

The detailed Linux docs have not yet been written so that's why the link does not work. The general guide should work just fine.
