### ISSUE TITLE
Allow users to trigger full sync

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1922]
Currently if something goes through the loop and since is later than some data that needs to be synced it is not easy to get that data from the server.

Current solution is to log out and back in again or clear cache.

We should make it possible for users to trigger full sync by themself.

Either by 
- a separate button in the menu 
  or 
- by counting the syncs triggered in a timeframe. ( like if it's third sync trigger in 1 minute then trigger full sync without the since param

**Comment by kutenai** [comment]
When I load toggl desktop, perhaps after not using it for a while, it might load up with "running" entries. It apparently has it's own "local" timer -- which is not in sync with any timers on the Toggl site. This seems like a design issue to me.. I mean, there needs to be a single source of truth. When Toggl Desktop (TD) loads, it should refresh from the server IMO, and if there is a server timer running get that information, rather than just keep running a local timer. 

Perhaps there is a limitation on the server site that keeps this from happening??

**Comment by IndrekV** [comment]
The latest beta releases do full sync on app start. So this should improve this situation. Beta releases for win, mac were released on 13th of July. Linux beta release was released on 11th of July

**Comment by IndrekV** [comment]
This is fixed with full sync on app start.
