### ISSUE TITLE
Pomodoro timer not taking account the "duration only" setting

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1954]
If duration only is selected and the duration is bigger than the pomodoro defined time the timer will be closed right after clicking continue. 

Pomodoro should start counting from the moment the timer was started.

**Comment by unmultimedio** [comment]
Hello! Look I've found this happening also in my mac, but I would think this is the expected behaviour, let me explain:

- Pomodoro should check any _on-going_ TimeEntry to check that doesn't exceed the limit defined by the user.
- When you start a task, and while it's active, you edit the *Start time* _(that's what I use to do when I remember late to track a task I started minutes ago)_, the TimeEntry is still an _on-going_ task, so it's expected it is stopped.
- You can just use the shortcut to continue with "a new task" with same description that last one, with a brand new timer for Pomodoro to start tracking.

IDK if this is the bug you're describing, sorry if it's not. At the beginning I was tempted to reported it as a bug, but then I realised, this should be the expected behaviour, right?

**Comment by IndrekV** [comment]
@unmultimedio  If you don't use `duration only` mode. The timer checks start time to calculate Pomodoro timer end time. If `duration only` mode is enabled Pomodoro will save start when entry is continued and calculate based on this saved timestamp.

this case is duplicate of #1984
