### ISSUE TITLE
Missing foreground font color

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#1961]
>the linux desktop app is missing (at least) the foreground font color in the (qss) style sheet.
I&#39;m using Plasma 5 on Gentoo with the &#39;Breeze Dark&#39; theme.

reported in desk case no. 319551

**Comment by ThePsyjo** [comment]
Didn't know everything is on GitHub, otherwise I would have posted it here ;)
I attach the screenshots I've made here.

![screenshot_20160801_125218](https://cloud.githubusercontent.com/assets/131891/17436224/01b9ca9e-5b16-11e6-8df8-0201e9f9dfca.png)
![screenshot_20160801_125436](https://cloud.githubusercontent.com/assets/131891/17436225/01b9d57a-5b16-11e6-9587-282a9a7f6a37.png)
