### ISSUE TITLE
Linux app crashed with "sigsegv memcpy avx unaligned"

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2072]
The only place that uses memcpy currently is the timeline so it might be connected to that

![image](https://cloud.githubusercontent.com/assets/842229/21223251/f3af8c42-c2ce-11e6-9771-8b47c9598253.png)

**Comment by MartinBriza** [comment]
It's possible we had some optimizations in place inside the binaries which were not handled well by computers with older processors (without the mentioned CPU instruction extensions). I think we don't do any radical optimizations in the packages after we've switched to CMake so this issue is most likely not valid anymore.
