### ISSUE TITLE
Grouping feature doesn't work on Windows (7.4.7)

### ISSUE THREAD

**Issue by jimmypoulin** [toggl/toggldesktop#2101]
The last update was supposed to introduce entry grouping. The feature is not working and it now creates new entries when we click play on a previous entry instead of continuing it like before.

![image](https://cloud.githubusercontent.com/assets/18073033/21818803/2c3fb470-d737-11e6-8675-22a22f9cc0e9.png)

**Comment by nicktoggl** [comment]
Hi Jimmy,

Could you go to your profile settings on our webpage, check to make sure grouping is enabled and then restart the app.

If grouping is already enabled on your profile page, please un-tick the option, click done before re-ticking the grouping option and pressing done again. Then restart the desktop app which should now be working correctly. You can find a guide to accessing the profile page at:(https://support.toggl.com/my-profile/)

If you still encounter problems please let us know.

**Comment by jimmypoulin** [comment]
It worked, thanks!

**Comment by Trost123** [comment]
Bump, same issue here - had to uncheck and re-check grouping option for this to work.
To be honest I'd never come up with solution myself. Why is offline app taking this option from online app settings? This should be in Toggl Desktop options too at least.
-
I've been waiting for this feature since October 4, 2016 (when it was released in online version of this app), sitting on a beta update channel, only to find out it's released month ago, but didn't appear because of this bug.
This is disappointing. Good thing I know how to use GitHub issue tracker, a typical user would just end up clueless or even more disappointed.

I enjoy using your free app, but this situation was plain frustrating.

**Comment by IndrekV** [comment]
@Trost123
The setting is a global user setting that affects both web and desktop app, this is why it's connected to the online settings.
