### ISSUE TITLE
Consider enhancing project search

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2110]
When you try to choose project by some word it only retrieves results(choices) if it contains key word only in the beginning of the project name string. So for example if i try to write "john" in intention
to choose project "Project of the John", it seems like there is no project of that kind beacuse it doesn't showing it there. It will only show it as a choice in dropdown if i start to write "project...". This works normally on the web version.
Requested by #393438

**Comment by GreenGremlin** [comment]
+1

Yes, please make search more robust!

- Search for all words entered, regardless of position
- Sort by relevancy

**Comment by GreenGremlin** [comment]
I believe this should be for all versions, not just linux

**Comment by IndrekV** [comment]
@GreenGremlin on other platforms it already works as described.  And now from the next release sot will it be on linux. Thank you for your feedback and for pumping up this issue.

**Comment by GreenGremlin** [comment]
@IndrekV I'm using version 7.4.55 on MacOS, and the project search on the time entry screen does not allow fuzzy search. If I have a project named "Update website header - Client A" and I type "Client A Update" I get no results. If I enter "website update" or "update header", I also get no results.

**Comment by GreenGremlin** [comment]
For MacOS, I believe this is where a change needs to be made.

https://github.com/toggl/toggldesktop/blob/master/src/ui/osx/TogglDesktop/AutocompleteDataSource.m#L151

It looks like `rangeOfString` only searches for exact matches of the search `key`. For project autocomplete, it looks like key is set to `project + ' - ' + client`. I am not an Objective C developer, so I have no idea how to fix it, otherwise I would submit a PR.

**Comment by IndrekV** [comment]
@GreenGremlin Good news I implemented the multi words search and it should be much better on mac from the next release. 

This issue was initially about linux autocomplete as linux autocomplete was very limited and neede d an upgrade. On linux it only autocompleted if the match was in the beginning of the project name or description.

**Comment by GreenGremlin** [comment]
Terrific! Thank you!

**Comment by tdgroot** [comment]
Way better, thank you!
