### ISSUE TITLE
Cannot show TogglDesktop window once it was minimized.

### ISSUE THREAD

**Issue by krekein** [toggl/toggldesktop#2232]
MacOS 10.12.5 and 10.12.6 - once the application was minimized, the window cannot be shown again. Have to quit the application and relaunch for the window to show again.

**Comment by IndrekV** [comment]
Is this similar to the issue described here #1932

**Comment by mikeybeck** [comment]
I have the same issue, and (in my case at least) yes, it is the same as the issue described.

I use uBar so disabling `Minimize windows into application icon` is a workable solution for me, because I don't use the dock anyway.  
Of course this probably isn't going to be the case for most people though.
