### ISSUE TITLE
Workspaces empty state

### ISSUE THREAD

**Issue by lizaPlotnikova** [toggl/toggldesktop#2248]
When the on Desktop app (MacOS, Linux or Windows) auto-syncs to the server, and is unable to find any existing WS (per toggl/backend#3851)

- [x] Deactivate time-tracking functionality (overlay and disable keyboard shortcuts and menu items)
- [x] Display an error message to the user
- [x] If user clicks “Force sync”, or automatic sync occurs and a WS is detected, hide the error message and re-enable time-tracking functionality

## Wireframe:
This wireframe demonstrates that time-tracking is blocked while the user has no workspaces.  In the final design, Indrek, should use styles used in the application specific to each operating system.

![ws empty state for desktop](https://user-images.githubusercontent.com/24964497/29430945-36f14378-8364-11e7-9294-17da35dba814.png)

**Error Message:**
>You no longer have access to your last Workspace. Create a new workspace on Toggl.com to continue tracking

>[Log in to Toggl.com](http://toggl.com/login)

>Created your new workspace? [Force sync ](url)

 _If there are unsynced time entries after the new workspace is created, the user will need to move the time entries to the new workspace manually_

**Comment by IndrekV** [comment]
Every platform now has missing ws view.

Things to do:
- [ ] Fix login button url to point to login page
- [ ] Styling fixes for the texts (win)

**Comment by IndrekV** [comment]
mac:
![missingws_macos](https://user-images.githubusercontent.com/842229/30398327-a849b742-98d8-11e7-9905-a9621cb4c408.png)
Win:
![missingws_win](https://user-images.githubusercontent.com/842229/30398328-a84fdd8e-98d8-11e7-9935-86263d62aa94.png)


Linux is also ready just haven't made a screenshot

**Comment by IndrekV** [comment]
Use `v9/me/workspaces` to check if user has workspaces or not.

**Comment by IndrekV** [comment]
Currently the proper way to test if a user has lost access to all workspaces is:
- If any request returns `403 Forbidden`
- do a get request to `v9/workspaces`. This returns 403 **only** if a user has no access to any workspaces.

**Comment by IndrekV** [comment]
This is handled to the state that if the user loses access to the last workspace all data is cleared, overlay with information is shown and the app is unusable until the user has solved the issue in the web app.

From my testing it currently seems that user is deleted altogether with the removal from the last workspace so if backend goes on and updates the behavior so that user is not removed and it is possible to create a workspace in an empty workspace state, I'll come back to this and implement it.

I also tested the web app and it worked the same. No way to log in when the user has no workspaces. Says the credentials are wrong.

An update about the current state of this development would be great @lizaPlotnikova
