### ISSUE TITLE
MacOS Desktop, SPACE hotkey not working

### ISSUE THREAD

**Issue by lecrouch** [toggl/toggldesktop#2298]
In the MacOS app, you can select timers with the arrow keys, but as per the docs, SPACE should continue the timer on the selected entry.

Upon keypress, it moves up one item on the list, further keypress' do nothing.

**Comment by IndrekV** [comment]
Just tested the issue. Space continues the single entry just fine. When the entry is a grouped entry it opens up the group. I think this part could be changed to make it better as also left and right arrow work as open close for the groups.

![space_macos](https://user-images.githubusercontent.com/842229/31574877-b437c28a-b0e1-11e7-9a24-d23c6879cfac.gif)

**Comment by lecrouch** [comment]
What version of Mac OS & Toggl are you running?  As my functionality does not match your gif.  Could there be a setting that I am missing?

**Comment by IndrekV** [comment]
No there is no setting. The SPACE did indeed open up the group. With the changes I made from the next release SPACE will always continue entry. 

If you don't have groups then the grouped mode is not enabled on the web app profile view.

**Comment by mikejohns7** [comment]
Why was this closed? It doesn't work at all for me either.

**Comment by lecrouch** [comment]
@IndrekV New thought, I have not run a build on the repo, I just spent a couple minutes poking around to find where the listeners may be.  Which makes me wonder, is the current downloadable .dmg on the same release version, or is it possibly trailing?  If there is a mis-match there that could explain why users are experiencing different functionalities.

Would you be willing to point me in towards where  in the repo key events are handled?  I started this issue report with every intention of fixing it myself, but I wouldn't be against saving some dig time :)

**Comment by IndrekV** [comment]
@lecrouch 
I've just release a new beta version with the fix [MacOs beta 7.4.71](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=beta)

The issue was fixed with https://github.com/toggl/toggldesktop/commit/5f572126eade40046a98c3104c5c457265e114e2

The SPACE key acts as default key to trigger keypress on view `first responder`. With two buttons in the time entry cell view (the group button and continue button) the `first responder` was set to the group button. What this commit did was disable setting the group button as `first responder` making the only first responder of the view the continue button.

I hope this gives some insight about the SPACE key functionality.
