### ISSUE TITLE
"This version of the app is not supported any more" appears on Windows app

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2338]
case/618004

Windows 10 user reports seeing this message "Every time I open the desktop app (e.g. after restarting the computer or even quitting the app)"

![image](https://user-images.githubusercontent.com/5687885/34508006-65b54860-f076-11e7-82fc-710edcd85b05.png)

Reinstall fixes, but only temporarily.

**Comment by nicktoggl** [comment]
v7.4.73 so up to date as well

**Comment by IndrekV** [comment]
This message is sent from the backend so I think it is a small hiccup in the backend. Probably already fixed as our backend masters are always alert. I'll close it for now. If there is more similar feedback we'll revisit this and dig deeper.

**Comment by dbau55** [comment]
Hi, I just received this same error.  Went to the website to download a new version, but upon install the error message still displays.

**Comment by jazzdragon** [comment]
Also happens on mac with 7.4.84
Timer would not start.

**Comment by kadrihvl** [comment]
@dbau55 @jazzdragon Current message in your desktop app is due to an outage we're having right at this minute. We've turned desktop apps off to get the webapp up and running again. As soon as it happens, we'll turn them back on. You can also follow along with our progress on our blog here: https://blog.toggl.com/connectivity-issues-update-jan-16/
