### ISSUE TITLE
Windows user can't login to the app

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2339]
User 2983950 is unable to log in to the Windows desktop app since re-installing it. We originally discussed this in Slack. Here's the archive ID: C029WCX0T/p1505994432000230

To see the logs open case 548632. The last note in the case contains links to all of the logs previously provided.

**Comment by natechr** [comment]
Here is the error in the log file:

**Comment by IndrekV** [comment]
The SSL exception happens when the user is using a proxy or some other network security tool that has its own SSL certificate. Toggl Desktop is unable to verify it is a legit certificate or not. The only possible solution is to make it somehow possible for user to verify the ssl certificate in the settings somewhere.

**Comment by natechr** [comment]
Are you able to provide any direction on how I would go about doing that?

Nate Cotter | C.H. Robinson Worldwide, Inc. | Business Analytics
952.683.3256 (w) | 763.443.8209 (m) |  nathan.cotter@chrobinson.com<mailto:nathan.cotter@chrobinson.com>
[cid:image001.jpg@01D099E1.D7ED9F70]

**Comment by IndrekV** [comment]
@natechr 
There is currently no solution for using Toggl Desktop with custom SSL certificate. The answer was in term that we should add a solution that would allow users to allow certain certificates to avoid SSL errors.

**Comment by natechr** [comment]
So is that a solution that will be worked on for the next release?

Nate Cotter | C.H. Robinson Worldwide, Inc. | Business Analytics
952.683.3256 (w) | 763.443.8209 (m) |  nathan.cotter@chrobinson.com<mailto:nathan.cotter@chrobinson.com>
[cid:image001.jpg@01D099E1.D7ED9F70]

**Comment by IndrekV** [comment]
@natechr 
Can't promise for next release, but we're going to look into it in the near future.

**Comment by IndrekV** [comment]
The ssl errors are because of local ssl certificate that the user uses. This cert is unknown and not trusted by toggl desktop and that's why the network communication fails. There is a workaround, but it should be used on your own risk. https://github.com/toggl/toggldesktop/wiki/Getting-Toggl-Desktop-to-work-with-local-proxy

We will not be implementing this to the app.

**Comment by natechr** [comment]
How do I add it? The solution says to add my local certificate to the file but there’s no instructions on how to do that.

**Comment by IndrekV** [comment]
@natechr  Check out the referenced file( cacert.pem ). It has some certs inside it already. You should copy your certificate file text to the end of this file. I also updated the wiki page to be more clear on that.

**Comment by natechr** [comment]
I see the .pem file in the toggle folder. What I don’t know is how to find my certificate file text that I’m supposed to add to the end of that file.

*************************************************************************************************************************
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the sender of the e-mail. The sender of the e-mail accepts no liability for any damage caused by any virus transmitted by this email. (IP)
*************************************************************************************************************************

**Comment by natechr** [comment]
I see the .pem file in the toggle folder. What I don’t know is how to find my certificate file text that I’m supposed to add to the end of that file. Can you help me out please?

*************************************************************************************************************************
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the sender of the e-mail. The sender of the e-mail accepts no liability for any damage caused by any virus transmitted by this email. (IP)
*************************************************************************************************************************

**Comment by natechr** [comment]
Hello, could you please reply?

I see the .pem file in the toggle folder. What I don’t know is how to find my certificate file text that I’m supposed to add to the end of that file. Can you help me out please?

*************************************************************************************************************************
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the sender of the e-mail. The sender of the e-mail accepts no liability for any damage caused by any virus transmitted by this email. (IP)
*************************************************************************************************************************

**Comment by IndrekV** [comment]
I've updated the article with instructions how to export cert from system cert storage https://github.com/toggl/toggldesktop/wiki/Getting-Toggl-Desktop-to-work-with-local-proxy#getting-the-proxy-cert-file

**Comment by natechr** [comment]
How do I know which certificate I need?



[cid:image001.png@01D428B3.215E6B40]

*************************************************************************************************************************
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the sender of the e-mail. The sender of the e-mail accepts no liability for any damage caused by any virus transmitted by this email. (IP)
*************************************************************************************************************************

**Comment by natechr** [comment]
How do I know which certificate I need?



[cid:image001.png@01D42FC3.9210A6C0]

*************************************************************************************************************************
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the sender of the e-mail. The sender of the e-mail accepts no liability for any damage caused by any virus transmitted by this email. (IP)
*************************************************************************************************************************
