### ISSUE TITLE
Mini Timer double click bug

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2354]
case/631295

"Sometimes a mouse-down on the mini timer opens the main toggl window, which can be annoying when I am simply trying to drag the mini timer out the way. This seems to happen on every other mouse down, which is presumably a bug related to some double-click to open behaviour. Toggl Desktop 7.4.73 Windows 10 Version 1709 (OS Build 16299.192)"

**Comment by andreasmischke** [comment]
Same issue here on Windows 8.1
Dragging the mini timer most of the time opens the main Toggl window.

Not sure about the double click thingy described above, but as a web frontend developer I expect click (open main window) and mousedown/drag (move mini timer) to be separate events

**Comment by IndrekV** [comment]
The issue is connected to the main window functionality. If user clicks the running timer in the main window the app shows edit view. With minitimer the functionality works the same.

I think it would make sense to open edit view from minitimer on double click and not single click so that we can avoid poping main window when moving around the minitimer window.
