### ISSUE TITLE
Users Unable to Use Current Windows App

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2391]
Receiving cases where users are unable to access the TogglDesktop app after trying to start it. 

Desk case/640424 is rather stereotypical of the cases we've been receiving: after trying to log in, they get a "TogglDesktop has stopped working" error and the program automatically closes. Manually clearing cache/cookies, as well as deletion and reinstall do not seem to help.

Desk case/640424 latest response also provided desktop crash logs for your reference.

**Comment by maritoggl** [comment]
case/642675 reported today, also includes logs for reference.

**Comment by IndrekV** [comment]
Fixed with b0a5a9e24672338c67470176185f48b808ee5717
Suggest users updating to latest beta.

Either go to About view and change the channel to "beta" and let the app download update or download the new beta version from our site

[win beta v7.4.122](https://toggl.com/api/v8/installer?app=td&platform=windows&channel=beta)
[mac beta v7.4.122](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=beta)
[linux beta v7.4.122](https://toggl.com/api/v8/installer?app=td&platform=linux&channel=beta)
