### ISSUE TITLE
Add support for json error messages

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2431]
Api will implement json error message in the future and we should add support of that to the lib.

json structure:

```
{
    "message" : "error message that is shown to the user"
}
```

**Comment by IndrekV** [comment]
Currently the error messages are predefined in the app and will be shown based on the response status code.

**Comment by IndrekV** [comment]
This change can be done int `https_client.cc` inside the `makeHttpRequest` method. Probably we have to check the content type after we have received the response
the line with `std::istream& is = session.receiveResponse(response);`

If the response is `json` we just copy the error message from the response to the `resp.body` and it should work.

**Comment by NghiaTranUIT** [comment]
FYI, Backend and Mobile team agreed on this structure.
```
{
  "error_code" : "FAILED_TO_DO_STUFF(format of codes is TBD)",
  "error_message" : "Stuff failed due to 2 being smaller than 5 (this message could be shown to the user if no localised message is available)",
  "parameters" : {
    "number1" : 2,
    "number2" : 5
  }
}
```

**Comment by NghiaTranUIT** [comment]
Here is my suggestion. 

Instead of define the `error` as a `std::string`, we introduce `Error`

1. Introduce class `Error`
```c++
    class Error {
    public:
        const uint16_t code;
        const std::string serverMessage;
        const std::string localMessage;

        Error(const uint16_t code, const std::string serverMessage): code(code), serverMessage(serverMessage) {
            localMessage = statusCodeToError(code)
        }

        bool IsNetworkingError();
        bool IsUserError();
        std::string MakeErrorActionable();
    };
```
2. typedef `Error` as `error`
```c++
namespace toggl {

    typedef Error error;

    const error noError = Error(0, ""); 

    typedef std::string guid;
}
```
3. Do minor refactor in library where we use `error`

## Props 
- We can keep legacy error logic by using `err.localMessage`
- We can show customization error by using `err.serverMessage`
- Encapsulate the error logic in Error class
- Able to extend Localization in `serverMessage`
- Less break the legacy code.

## Cons
- Many changes occur in the Library
- More responsibility

**Comment by MartinBriza** [comment]
I don't think we need to create a new class to handle the messages until we have a use for anything other than the message.
We could just get the JSON, extract the error message string and pass it to the rest of the app as we have done it until now.
Or is that not possible?

**Comment by NghiaTranUIT** [comment]
The minimal solution is opening at #2770 PR. Basically, it will work with static error string.

On the other hand, we should consider to refactor the error mechanism in library as soon as possible since it's pretty **hard** to extend new error feature, such as Error Localization, Error Parameters, ...
