### ISSUE TITLE
Emoji problems in ubuntu 18.04

### ISSUE THREAD

**Issue by SergiArias** [toggl/toggldesktop#2441]
In 17.10 everything worked fine, but after 18.04 (which support color emoji), projects with emoji cannot be seen.

This makes the app unusable :(

![imatge](https://user-images.githubusercontent.com/13618783/39694942-3689f818-51e9-11e8-9f64-cd4fe77770e2.png)

![imatge](https://user-images.githubusercontent.com/13618783/39694967-4d3ac894-51e9-11e8-894f-5950a08a794c.png)

**Comment by MartinBriza** [comment]
This is pretty likely because:
1) you don't have the required color emoji fonts installed in your system. 
2) or, this is the `.tar.gz` that ships its own fonts
Possible solutions are:
1) Install an emoji font, like `google-noto-emoji-fonts` (may be called something else in your distro, this is from Fedora)
2) Try if `v7.4.410` fixes this for you.

In any case, this is either fixed already or not an issue I can do something about at all. HOWEVER, in case this didn't help, please reopen this issue and we'll take a further look at it. Then please specify what exact OS you have (and which Desktop Environment) and also what type of Toggl package and which version you tried. I'll try to reproduce your exact configuration to see what the issue could be.
