### ISSUE TITLE
Resume Time Entry

### ISSUE THREAD

**Issue by Dapacruz** [toggl/toggldesktop#2559]
A couple years ago, it was possible to resume a time entry and maintain a single entry. Today, when resumming a time entry, a new entry is created. It would be great to have the option of maintaining a single time entry.

**Comment by IndrekV** [comment]
We replaced the entry continue functionality with grouped entries. You can group similar entries together so that they show as one in the time entry listing. You can enable this feature from the web app profile view (the setting also applies to desktop app). See more info about Grouped entries https://support.toggl.com/the-timer-page/#grouping
