### ISSUE TITLE
Task name replaced from previous selected

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2593]
1. Select a task with clicking on a task
2. Close a popup
3. Name of task changes to a previous selected task
4. Repeat again with another task
5. Name of the new task is replaced with old one

![4pnd0-2 2018-10-16 11-58-10](https://user-images.githubusercontent.com/2384694/47008842-60ac9980-d13b-11e8-9251-11c873caa5b5.gif)

Happens not really often. Still really annoying, since user data gets lots.

**Comment by Leland** [comment]
Happens to me frequently, it's incredibly annoying. I've lost a lot of important data this way. It's exacerbated by both #2588 and #2588.

**Comment by iDevForFun** [comment]
Same ... happens frequently. I lose the information I need to bill my clients.  Can't undo ... can't recover the lost data ... desktop version is unusable with this issue. (macOS Mojave 10.14)

**Comment by IndrekV** [comment]
Let's put it into the current milestone and see what's up. I think the issue is caused by the focusing logic. Also undo would make sense.

**Comment by Leland** [comment]
Appreciate it, this has been a big issue on my team (where Toggl is the backbone of our workflow)

**Comment by effektsvk** [comment]
I had a slightly different way this happened to me but it is the same issue. Just want to add that it was happening to me on macOS Sierra (10.12) and on Mojave (10.14) so it is not an OS related issue. It is kind of annoying to see this bug in stable... I've tried stable, beta and even dev, it is glitched everywhere, if I have some spare time and manage to build some older version where this is working, I will let you know.

**Comment by Leland** [comment]
I have a feeling that the reason that reverting to even old (known good) stable versions isn't fixing this is perhaps because it's not an issue with the app itself.

I'm not familiar with the architecture of the app (and task name/autocomplete), but I've been persistently hitting issues with my app being wildly out of sync with the web UI.  Could be related. Here's a shot of my local Toggl app, and the web view for the same day:

![screen shot 2018-10-25 at 5 51 57 pm](https://user-images.githubusercontent.com/714017/47532613-ceb13900-d87e-11e8-861d-dece6d9cc467.png)

I'm on a stable ethernet connection, so internet issues should not be the cause here.

**Comment by IndrekV** [comment]
Hey guys! I've made some tweaks so that the data in edit form is always cleared when popup is closed. This should avoid this issue with old data overwriting the new data.

I've created a new build with the fix. I tested it and in my tests could not replicate it anymore. If anyone wants to verify and test here is the link to the build https://github.com/toggl/toggldesktop/releases/download/v7.4.283/TogglDesktop-7_4_283.dmg

I've also pushed the Undo feature up our todo list as I agree it is a needed feature to add.
