### ISSUE TITLE
Pomodoro mode triggering despite being disabled

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2599]
Intercom 18854882243:

_I am attempting to record time for a task, but the timer will not record beyond 7 seconds. it automatically switches to a pomodoro break for every task that I attempt to track, regardless of whether or not I have the pomodoro timer turned on. Let me know if you would like me to send additional information regarding this error._

Windows 7.4.252

(Full log in case)

**Comment by NghiaTranUIT** [comment]
Regarding this issue when the Pomodoro triggers regardless on/off Pomodoro state in Setting. I investigated and unable to replicate it on my machine. 

## Brief result of my Investigation 
### Windows UI code is understandable
https://github.com/toggl/toggldesktop/blob/bbce502d0c7b9831203ff45dce4414292cc64fc8/src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml.cs#L21
https://github.com/toggl/toggldesktop/blob/bbce502d0c7b9831203ff45dce4414292cc64fc8/src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml.cs#L25-L38

Basically, it registers the func `onDisplayPomodoro ` and execute whenever the `Toggl.OnDisplayPomodoro` trigger from library.

This logic is small enough and there is error here, so I investigate further in library codebase.

## Race Condition
However, there is suspicious code in library, which I suppose it's the root of problem. 

### Modify settings_ in Main thread
<img width="315" alt="screen shot 2018-12-17 at 17 25 34" src="https://user-images.githubusercontent.com/5878421/50081719-bd9efb80-0221-11e9-93ba-d605010958f6.png">

https://github.com/toggl/toggldesktop/blob/bbce502d0c7b9831203ff45dce4414292cc64fc8/src/context.cc#L785

We try to modify the `setting_` in main thread whenever we update new state in Setting .

### Read data in background thread
<img width="311" alt="screen shot 2018-12-17 at 17 26 24" src="https://user-images.githubusercontent.com/5878421/50081776-dd362400-0221-11e9-901d-3cd83d616057.png">

https://github.com/toggl/toggldesktop/blob/bbce502d0c7b9831203ff45dce4414292cc64fc8/src/context.cc#L4066-L4069

This logic will check if we enable `settings_.pomodoro` or not, but we're reading it from background thread.

### Result
- In some edge case, the race-condition occurred unexpectedly and it results in the Pomodoro notification trigger even the state is OFF.

It could be the problem, which we're looking for 🥇 

### Suggestion
- Introduce serial queue or concurrent queue with barrier in order to prevent the race-condition.

**Comment by IndrekV** [comment]
We're unable to reproduce this. The code seems to be correct and the fact that the Pomodoro triggers after 7 seconds is very strange as you can not define Pomodoro in seconds. The user got it working by clearing the local cache.
