### ISSUE TITLE
Autocomplete suggestions list empty in some scenarios

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2622]
Screencast sent by user shows that:
- user continues an entry by pressing the arrow in the listing
- opens edit for the running entry right away
- goes to project field to starts typing
- Autocomplete does not show any suggestions
- When the user closes edit window and reopens it, autocomplete items are shown as expected.

**Comment by maritoggl** [comment]
Also reported by user in [conversations/20091900532](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20091900532)

**Comment by NghiaTranUIT** [comment]
## My investigations

There are three suspicious places I believe could lead to this problem.
1. In someways, `[self showAutoComplete:NO]` is buggy and keep hide the AutoCompleteTableView.
https://github.com/toggl/toggldesktop/blob/9ea1df83aa324adfc54e04d01cbee21622dbd17f/src/ui/osx/TogglDesktop/test2/AutoCompleteInput.m#L151

However, every time the text input changes in EntryEditViewController, it will filter the result in [self findFilter:] and reload and show or hide the table view appropriately if the `self.filteredOrderedKeys.count > 0`.

2. Somehow, `self.orderedKeys` in `LiteAutoCompleteDataSource.m ` is empty due to race-condition. So, the table view is hidden regardless of user's input or filter actions.

However, those accesses are safe-thread by using `@synchronized(self)`
https://github.com/toggl/toggldesktop/blob/9ea1df83aa324adfc54e04d01cbee21622dbd17f/src/ui/osx/TogglDesktop/test2/LiteAutoCompleteDataSource.m#L76

3. Maybe, there is a bug in library, if `kDisplayProjectAutocomplete` is never executed, then the `self.orderedKeys` is empty too.

## Result
I'm unable to replicate it on latest `master` even using [Network Link Conditioner](https://nshipster.com/network-link-conditioner/) to simulate 3G connection, which is slow and unreliable network.

I suppose that this issue could be resolved implicitly by the refactor on `TimeEntryEditViewController` and Diff PR.

**Comment by IndrekV** [comment]
I'll do another round of tests to see if I can replicate this. If not, we'll close this.

**Comment by NghiaTranUIT** [comment]
I don't think this ticket is valid to choose since we re-implementation entire AutoComplete Suggestion feature in #2906. Once it's approved, we could close this ticket 👍

**Comment by IndrekV** [comment]
Fixed with new autocomplete UI
