### ISSUE TITLE
Toggl Mac desktop app won't start up after being closed

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2637]
A user reported that ever since upgrading to Mac OS Mojave his Toggl desktop app for Mac works fine when it's initially started, but after they shut down their computer the app will not start up the next time. 

The user found that a fresh re-install fixes things until they shut down their computer again. Clearing the app's local data does not help. 

they also say that _"When I try to start the app I get the generic Mac OS Application icon, not even the Toggl One"_

Conversation: 19619245258

**Comment by VeljkoTN** [comment]
@IndrekV the user is expecting an update here, let me know if there is anything I can share

**Comment by IndrekV** [comment]
This issue has appeared on previous versions of macOS and is quite hard to figure out as it isn't specifically caused by our code. It's caused by something mixing up about our app close logic and the system shutdown. The generic icon means that the correct icon and app files have been deleted. Getting to the bottom of this takes some time as there is no easy way to pinpoint the reason for this happening.
