### ISSUE TITLE
App icon is missing after icon logic update

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2716]
### 💻 Environment
Platform: macOS

### 🐞 Actual behavior
The app built by our buildbot is without Toggl logo. Default system icon is shown instead.

### 💯 Expected behavior
Buildbot builds with the correct icon

### 📦 Additional info
Might be caused by building with sdk 10.11 maybe it does not support the Icon Assets

**Comment by NghiaTranUIT** [comment]
After investigating, it revealed that we have to build Toggl by using
- OS >= 10.12
- Xcode >= 8.0

Because ImageAsset is officially supported

**Comment by IndrekV** [comment]
Maybe one of these solutions will help https://stackoverflow.com/questions/46109835/app-icons-not-included-in-build-from-xcode

Also it is strange that the icon is there in the build folder but when we unpack the app from dmg it's gone.

**Comment by IndrekV** [comment]
The issue might be caused by packing the app into dmg. The dmg image has a size limit and if the updated icons make the app bigger than the image it can be an issue. The other possible cause is that something is just not packed into the dmg properly.

**Comment by NghiaTranUIT** [comment]
Regarding this [StackOverflow's solution](url
https://stackoverflow.com/questions/46109835/app-icons-not-included-in-build-from-xcode), I don't think that it could solve our issue because it mentions about the missing icon in Xcode 9 by using wrong icon format.

It's totally different with our scenario, which is that the Xcode version (OS X 10.11) in buildbot didn't recognize Image Assets appropriately.

On the other hand, I tried to archive Toggl by Xcode 10.1, and it bundled the icon properly. So I suspect that our the version of Xcode in buildbot could be a problem.

**Comment by NghiaTranUIT** [comment]
Can you confirm what the current value of `$(XCODELEGACYSDK)` is in our buildbot 🤖 server?

**Comment by NghiaTranUIT** [comment]
I'm setting up to access directly to our buildbot 🤖, let see what the problem is 🏄‍♂️

**Comment by NghiaTranUIT** [comment]
Brief result from last investigation on Mini Buildbot 🤖 

Basically, I tried to archive **successfully** Toggl (has correct logo) with macOS 10.14, Xcode 9.0 and config `-macos10.11` in my machine.

However, in Mini 🤖 , which is macOS 11.12, Xcode 9.0 and config `-macos10.11`, for some mysterious reasons, the icon asset wasn't bundled appropriately.

I'm intending to upgrade Mini to Xcode 9.1 or Xcode 9.4 to see whether the issue is gone or not.

**Comment by NghiaTranUIT** [comment]
After detail investigation, it turns out that I updated all Project Setting in Xcode 10.1 in #2689. 
Consequently, this setting doesn't match well with Xcode 9.0, so there are certain project warnings ⚠️ .

I will re-config this setting, then double check again 🤖

**Comment by NghiaTranUIT** [comment]
After many testing combinations in Xcode 9.0 (10.11 mini bot) and Xcode 9.0 (10.14 my workspace), I believe that there are mysterious reasons, which are related to **OS** rather than the version Xcode, which cause our Icon problem.

## Steps to replicate
1. Download this IconTest ([Github](https://github.com/NghiaTranUIT/iconTest))
2. Make sure Minimum Deployment OS is 10.11
4. Product -> Archive 
5. Export without signing 
6. Open *.app and check the assets.car by [AssetCatalogTinker](https://github.com/insidegui/AssetCatalogTinkerer/releases)
7. Check whether the icon is existing 

## OS Specific 
We repeat Steps to Replicate twice in both following workspace.

| Workspace        | Xcode           | OS  |
| ------------- |:-------------:| -----:|
| Mini bot      | 9.0 |   10.11 |
| My workspace     | 9.0      |   10.14 |

## Result
| Workspace        | Icon in assets.car           |
| ------------- |:-------------:|
| Mini bot      | NO |  
| My workspace     | YES     |

**Comment by NghiaTranUIT** [comment]
## How macOS get the icon of IconTest.app.

Regarding **macOS < 10.13** (Mini buildbot 🤖 ), macOS acquire the icon from `IconTest.app/Contents/Resources/AppIcon.icns`

Whereas, **macOS >= 10.13** (My workspace) prefers `IconTest.app/Contents/Resources/Assets.car` if `Assets.car` is existing or get the icon from `AppIcon.cns` (backward-compatible)

## actool
After deep investigation, I realize that `actool` is responsible for bundling our icons to `asset.car` file.

According to [Manpage's actool](http://www.manpagez.com/man/1/actool/)
```
--app-icon name
              Can  be  combined  with --compile to select an app icon. **The app
              icon will either be copied into the output  directory  specified
              by  --compile,  or into the generated CAR file, depending on the
              value of --minimum-deployment-target.** Deploying to  macOS  10.13
              or  iOS 11.0 and later will cause the app icon to be included in
              the generated CAR file. A partially defined image is still  gen-
              erated  into  the  output path, but this behavior may go away in
              the future. This flag also causes actool to declare the app icon
              in  the  patrial info plist component specified by --output-par-
              tial-info-plist.
```
It means that if we archive Toggl under macOS < 10.13, `actool` always prefers copying our icon into output directory rather than bundling inside the CAR file. 

Consequently, the set of icon is missing in CAR file, and results in the missing icon in OS >= 10.13.

It's reasonable to explain why [previous result](https://github.com/toggl/toggldesktop/issues/2716#issuecomment-449944691) has different results even the app configuration is same.

### actool example
```
    /Applications/Xcode.app/Contents/Developer/usr/bin/actool 
    --output-format human-readable-text 
    --notices 
    --warnings 
    --export-dependency-info /Users/mini/Desktop/iconTest/build/IconTest.build/Release/IconTest.build/assetcatalog_dependencies 
    --output-partial-info-plist /Users/mini/Desktop/iconTest/build/IconTest.build/Release/IconTest.build/assetcatalog_generated_info.plist 
    --app-icon AppIcon --enable-on-demand-resources NO 
    --sticker-pack-identifier-prefix com.mac.mini.IconTest.sticker-pack. 
    --target-device mac --minimum-deployment-target 10.11 
    --platform macosx --product-type com.apple.product-type.application 
    --compile /Users/mini/Desktop/iconTest/build/Release/IconTest.app/Contents/Resources /Users/mini/Desktop/iconTest/IconTest/Assets.xcassets
```

## Final result
There is no options / choices to force `actool` to bundle Toggl's icon to CAR file in order to work with latest macOS (>= 10.13).

## My suggestion
1. Just keep the revert PR as it is.
2. Upgrade Mini boot to macOS 10.13.

I prefer the first options since it's effortless.

**Comment by IndrekV** [comment]
Let's go with the 1. suggestion and keep the old icon logic. If we get more reports about missing icons we will take another look at it.

At least we have a lot of info now about the logic the macOS has for bundling icon. Great documentation @NghiaTranUIT . Thank you for being so thorough.
