### ISSUE TITLE
Add more log to investigate "Sync error"

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2756]
### 📒 Description
There was a report (**conversations/20352441233**) that his/her Entry List was unable to sync there list to server. However, we not sure that the root of problems whether from client or server.

We have to add more logs if we detect this case again.

### ⭐️ Why do you want this?
Easier to investigate the side, which is responsible for "Sync error"
1. If it was from server -> Report to backend team with X-Toggl-Request-Id
2. If it was from client -> Investigate why?

### 💻 Environment
Version Beta v7.4.330
Platform: macOS 10.14.2

**Comment by IndrekV** [comment]
This is fixed with 488fb120d0fd81b9f4f7ac46b10b093966c87ab6. The description of the issue matches to the scenario. When the user stopped the entry in some cases the entry data was not cleared and starting the next entry failed as the app still had data that last running entry was tracking.

**Comment by konradjurk** [comment]
@IndrekV This problem is **not** fixed. I have local time entries that won't sync back to your backend even with the latest release of the Mac Desktop App that I just downloaded. It is version 7.4.330. It is labeled "pre-release" although I am in the stable channel by the way. Could you please fix these problems ASAP

**Comment by konradjurk** [comment]
@konradjurk @IndrekV Ah, I was using a different account in my browser than in the Desktop app. Wouldn't be neccesary if you'd allow concurrent timers 😄but this was clearly my fault
