### ISSUE TITLE
Toggl Desktop regularly crashing during search

### ISSUE THREAD

**Issue by betagoo** [toggl/toggldesktop#2801]
Windows 10 x64.
Toggl Desktop regularly crashing during search.
1. I stop the current time tracking.
2. I click on the search field - What are you doin?
3. Start typing the client name.
4. Now application display founded time entries and projects.
5. Freeze at the moment.
6. The list of founded time entries and projects disapearing.
7. If I try to repeat searching, and I click on search field or use backspace button to remove last letter to trigger search list, in this moment application auto close (without any error).

**Comment by IndrekV** [comment]
Please send feedback from the app so we can get log files and can see at what point the app freezes.

**Comment by betagoo** [comment]
Sended. I paste link to this page into description.

**Comment by Michelle112** [comment]
Log files are [here](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/20777468335).

**Comment by ricotheque** [comment]
@IndrekV, @betagoo reached out further with more details. It's possible that ESET Smart Security Premium might be blocking the connections. Here's what their support said:

_It is not possible to analyze compressed content, so it has to be decompressed in the product. That leaves us with two options: pass the compressed or plain content to the browser. The first option would mean that the content has to be decompressed twice. Please note that in HTTP it is not possible for a client to request compressed content only, all it can do is declare support for some co mpression algorithms. Because of that every RFC-compliant implementation has to be able to handle non-compressed content. Since there are various buggy implementations being used, we pass unchanged server replies to non-browsers instead. Accept-Encoding is not modified, only Content-Encoding in replies is.

ESET as part of protocol scanning analyzes network communication also in terms of compliance with RFC standards. If something abnormal appears in the communication - it can be blocked / cut. Because this element is in no way configurable - the only effective solution in this case is to set appropriate exclusions in the protocol filtering module. This can be done for both applications and specific IP addresses._

For now @betagoo has excluded the desktop app exe from the filtering protocol, and will update us if this has an effect.

**Comment by betagoo** [comment]
Probably 99,99% the reason is ESET protocol filtering, and exactly RFC communication:

> If something abnormal appears in the communication - it can be blocked / cut.
