### ISSUE TITLE
Revisit the Windows build process

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2852]
Building the Windows app is quite challenging for people who have not built it before in the past, it is a question if it happens because there are issues in our VS project or in the way in which we ship dependencies. I suggest we (or me, personally) take a look at it and improve it for the future.

It could also be worth looking into using CMake to build the library / generate the VS project. 

### 💻 Environment
Platform: Windows/Linux
OS Version: Windows 10 and the newer Visual Studio, the more issues
Toggl Version: `master`

### 🐞 Actual behavior
It's hard/unclear how to build the Windows app, there is a lot of unused configurations etc. 

### 💯 Expected behavior
Only Release/Debug and maybe Production/Development build configurations should be present. It should be easy to setup the build environment without tweaking the configuration, both for other developers and our build bots. Only installing the crucial dependencies should be necessary.

**Comment by NghiaTranUIT** [comment]
Totally agree. It took me couple hours to figure it out how to build the app 🤐. It's a good starter step for a windows-mate 👨‍💻

**Comment by IndrekV** [comment]
Currently, `Debug` does not work at all because of some file path issues. There is a PR to fix it created by @NghiaTranUIT 

`Release` is used to build a production app. (it connects to live database)
`Release_VS` is used for development. (it connects to staging database)

I agree that we should upgrade to the newest Visual Studio.

**Comment by NghiaTranUIT** [comment]
Here is my steps in order to run Window from fresh Window 10 installation. Maybe it's useful for someone take this ticket.

1. Install Window 10 64 bit
2. Install Visual Studio 2013 (It includes v120 tool-build)
3. Install [ActivePerl](url
http://www.activestate.com/activeperl/downloads)
4. Install Visual Studio 2017 (make sure we select C++ Development, Window WPF and Window 10 SDK)
5. Clone Toggl repository and opening it the project in `/src/ui/windows/TogglDesktop/TogglDesktop.sln`
6. When opening the project by VS 2017, the pop-up will present to upgrade our tool-build. Just **skip** ⏩ it.
7. Select `Release_VS` scheme in Menu Bar and Run
8. Profit 💰

**Comment by NghiaTranUIT** [comment]
One more thing, we couldn't debug by checkpoint if we test with `Release_VS` scheme.

**Comment by IndrekV** [comment]
The debug breakpoint issue is fixed in master with c74bb44

**Comment by skel35** [comment]
I think we can close this issue now. After #3057 the only requirement for Windows development is to install VS 2019 with a few options ticked during installation, the configurations were cleaned up too.
There is still a Debug mode issue which will be addressed separately #3060, but other than it's pretty simple.
