### ISSUE TITLE
Entry title cursor inconsistently jumps to end of line

### ISSUE THREAD

**Issue by szpasztor** [toggl/toggldesktop#2883]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.3
Toggl Version: 7.4.330

### 🐞 Actual behavior
When typing the title of time entries in the app, the cursor unexpectedly jumps to the end of the line, further typing adds characters there. The jumping behavior happens irregularly with no apparent pattern.

### 💯 Expected behavior
The cursor should not jump around.

### 🔨 Steps to reproduce

1. Open toggl desktop
2. Add multiple projects, each with multiple tasks 
3. Add/edit many entries with titles

**Comment by effektsvk** [comment]
I've noticed that it happens when you write something and auto complete finds at least one result. Example flow:
1. Create first time entry, e.g. "Testing A feature"
2. Start creating second one
3. Click on "Testing A feature" to get the title auto filled
4. Start editing second entry
5. Try to rename to e.g. "Testing B feature" by placing cursor to the character, make any change (removing any character is enough)
6. Cursor jumps to the end

This is incredibly annoying issue, I'd fixed it myself if I had the time and knowledge of C++/C#.

**Comment by IndrekV** [comment]
This will be fixed with the next release that has a total design update. (planned beta release is next week)
