### ISSUE TITLE
Input Field Duration of Running Timer is Jumpy (Mac)

### ISSUE THREAD

**Issue by chrisspiegl** [toggl/toggldesktop#2943]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.407

### 🐞 Actual behavior

When editing the duration of the running timer it's a jumpy experience and often annoying. The time I enter get ignored and the cursor jumps out of the window. 

### 💯 Expected behavior

I often forget to start a timer and would then like to just start with 5 minutes for example. I start the timer, open it and start typing in the duration field, but since there is a running refresh on it jumps out of the field.

My expectation would be that once I start typing in the field the timer does no longer update the field and lets me finish my input cleanly. 

### 🔨 Steps to reproduce

1. Start Timer
2. Open Running Timer Edit Field
3. Click Curser into Duration field
4. Input a new number or something like "33min"
5. It sometimes works and sometimes doesn't.

**Comment by NghiaTranUIT** [comment]
This issues is fixed when we merged the Time Entry Editor #2906.

I was actually able to replicate this bug in `v7.4.407`, as the report stated, but I couldn't reproduce it anymore in master at https://github.com/toggl/toggldesktop/commit/d528d99f997f29215a8878ce6d340fa4aea8cb92

## Solution
This issue was fixed in https://github.com/toggl/toggldesktop/pull/2906/commits/cc9e806a4e7e0246e9c494a5aaf711d68760e94e#diff-fdce56582ba6db00741c5b24df6a47e0R313, when we introduce the guard to prevent updating the duration text field if it's first responder.

## GIF
![2019-05-27 18 04 37](https://user-images.githubusercontent.com/5878421/58416037-8b37db00-80aa-11e9-8b5d-84018f0ea7a4.gif)

**Comment by chrisspiegl** [comment]
@NghiaTranUIT I tested it in the new Dev release 7.4.420 and it's no longer a problem. I also much prefer the new layout and field styling. Very nice work 💪.
