### ISSUE TITLE
UI Tweaks for new mac design

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2980]
### 💻 Environment
Platform: macOS

### 📒 Description

- [x] ESC should close edit popup when there is no opened autocomplete popup
- [x] Clicking on the dark overlay in main window autocomplete should close the dropdown
- [x] After signup when users starts entry the first empty state changes to spider. It should stay the same as long as at least 1 entry has been in the list. As we show 9 entries in the list and actually load more we could detect if spider should be shown that way somehow
- [x] Unable to open up “create client” with clicking the arrow in client field (When it’s a fresh account and there are no clients) [Might be same with project autocomplete]

**Comment by NghiaTranUIT** [comment]
Regarding the "Empty state, spider or welcome", and from our current implementation, there is now way to distinguish two scenarios:

1. Old users: Has >= 1 time entries, which were created over 9 weeks.
2. Complete new user after sign-up: Has 0 Time Entry.

From what I debug, both scenarios, the Toggl Library returns
```objc-c
- (void)displayTimeEntryList:(DisplayCommand *)cmd {
    cmd.timeEntries; // -> 0 entries
    cmd.show_load_more; // => true
}
```

Therefore, I have to do a trick in order to identify the new user by logging the `kUserHasBeenSignup` in NSUserDefault after the sign-up

https://github.com/toggl/toggldesktop/blob/60bd393ddaf9ff69be6acb0ca89df73e1a496c87/src/ui/osx/TogglDesktop/TimeEntryListViewController.m#L664

Then reset during log-out

https://github.com/toggl/toggldesktop/blob/60bd393ddaf9ff69be6acb0ca89df73e1a496c87/src/ui/osx/TogglDesktop/test2/AppDelegate.m#L1074-L1075

## Result
1. After sign-up as a new user, the Welcome screen is always presented
2. After creating new TE, the Welcome screen is disappeared
3. Delete this time entry -> The Spider appears 
4. Spider screen also appears in Old User 

## Drawback 
- If the new user logout without creating any TimeEntry, then they log-in -> The Spider appears again.

## Alternative solution
This hack is result of the Library since it lacks capability to know that if user has already had any TEs or not.

I propose that we should improve this logic, so we could get rid this hack.

**Comment by NghiaTranUIT** [comment]
However, your report is correct @IndrekV , and it was fixed in https://github.com/toggl/toggldesktop/commit/60bd393ddaf9ff69be6acb0ca89df73e1a496c87 🙌

**Comment by IndrekV** [comment]
As long as the first login after signup works ok the other logins don't matter. What I mean is that if user does not create any entries and logs out it's ok to show the spider next time they login to the account.
