### ISSUE TITLE
Unsynced entry is not correctly displayed when app is relaunched

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3128]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.3
Toggl Version: 7.4.471

### 🐞 Actual behavior
Unsynced entry is shown as a synced entry if the app is relaunched.

### 💯 Expected behavior
Unsynced entry should be displayed as unsynced.

### 🔨 Steps to reproduce
1. Go offline
2. Log a time entry
3. Now It is correctly shown as unsynced (red warning sign on the bottom right)
4. Quit Toggl Desktop
5. Start Toggl Desktop
6. Now the red warning sign is not shown

### 📦 Additional info
![image](https://user-images.githubusercontent.com/16451391/61776935-b3229100-ae04-11e9-9e6a-9bc8a186af5c.png)

**Comment by NghiaTranUIT** [comment]
I suppose that this issue is heavily related on library rather than macOS on particular. From what I observe that the TimeEntryViewItem's unsynced 
https://github.com/toggl/toggldesktop/blob/b11236614b92445a5388b72fe8f819860e0f86f8/src/ui/osx/TogglDesktop/TimeEntryViewItem.h#L28
is **unreliable**.

Here is my investigation:

## Why doesn't the Red Warning sign show after re-launch the app?
- Toggl Desktop doesn't locally store the Unsync in database anywhere. It means that everytime the app launches, all `unsynced` value of all Time Entry are initialized by `false` -> Result in no 🔴 indicator in UI
- After the period of time, the Syncer in Library gets the error result (unreachable network) -> Update the `unsynced` -> the Error Show 
- Sometime, after the app launches, the syncer doesn't run. Thus, I have to explicitly click "Sync" on Menu Bar

## Proposal 
- Store `unsynced` in database and receive it during the app initialization.

**Comment by IndrekV** [comment]
We actually know that time entries are not synced as we know which ones need syncing. They are markes as `dirty` or something similar. Maybe it's possible to send this info to the ui at app start.

On other cases we should not send the info to UI as it would result the `unsynced` icon to flicker always when sync is about to happen.
