### ISSUE TITLE
Editing time entries using Autocomplete doesn't contain Tags

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#3204]
### 💻 Environment

Platform:  macOS
OS Version:  10.14.16
Toggl Version:  7.4.484.

### 🐞 Actual behavior

Editing an empty time entry by using autocomplete leaves out Tags so Tags have to be added manually

### 💯 Expected behavior

Autocomplete should populate Tags as well rather than omitting them

### 🔨 Steps to reproduce

1. Start an empty timer (just clicking the Play button)
2. Click to edit the time entry 
3. In the description, type the name of some of your previous time entries that contain Tags (relying on the autocomplete)
4. The new time entry will now contain the same description, same Project but without any Tags

### 📦 Additional info

![desktopbug](https://user-images.githubusercontent.com/19727123/62940456-ef2d8e00-bdd3-11e9-9d08-42e4e8aff635.gif)

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/23191044625)

**Comment by zdericnina** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/23236069302)

**Comment by zdericnina** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/23253299868)

**Comment by NghiaTranUIT** [comment]
## Library issue
After investigating this issue, it turns out that it happens in the Library and I'm not sure how to fix it.

Here is the detail report.

## How Editor render tags
1. Whenever the library render, it will post `kDisplayTimeEntryEditor` notification this func is executed 
https://github.com/toggl/toggldesktop/blob/97b5c3fb7f8062d94799218a38a43d186bb1841f/src/ui/osx/TogglDesktop/TimeEntryListViewController.m#L333
2. The Editor will fill all data of the selected TimeEntry at
https://github.com/toggl/toggldesktop/blob/97b5c3fb7f8062d94799218a38a43d186bb1841f/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift#L49

=> Basically, if the TimeEntryViewItem includes the Tag, the Editor will 100% render the tag views.

## How we select autoCompleteItem
1. As soon as we select the Description AutoCompleteItem, this method will update in library
https://github.com/toggl/toggldesktop/blob/97b5c3fb7f8062d94799218a38a43d186bb1841f/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift#L448-L449

2. However, the Library will notify `4` time `kDisplayTimeEntryEditor `, and it makes the Editor render 4 times as well.
3. The problem is that the 3 first times, the TimeEntryViewItem in this `kDisplayTimeEntryEditor` has tag data, but the last one is `NOT` (I debugged, and this noti comes from the Syncer)
4. It results in Empty Tag 

## Try
I tried few fix in this https://github.com/toggl/toggldesktop/blob/97b5c3fb7f8062d94799218a38a43d186bb1841f/src/context.cc#L531
but it didn't work well.

@IndrekV Do we have any clue?

**Comment by NghiaTranUIT** [comment]
The reason why we have 4 `kDisplayTimeEntryEditor` notifications, one caused by https://github.com/toggl/toggldesktop/pull/3215/files

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23253299868)
