### ISSUE TITLE
Time entries list missing in Macos Desktop 7.4.484

### ISSUE THREAD

**Issue by adamshostack** [toggl/toggldesktop#3253]
### 💻 Environment

Platform: MacOS 
OS Version: 10.13.6
Toggl Version: 7.4.484 (web install, not apple store)

### 🐞 Actual behavior
The toggle window shows only the current tasks.

### 💯 Expected behavior
The toggle window has a list of recent tasks, as shown in https://support.toggl.com/en/articles/2410817-toggl-desktop-for-mac (to be more precise  - https://downloads.intercomcdn.com/i/o/137902648/ec8c4a8087d5add88d6dd5fa/image.png 

### 🔨 Steps to reproduce

1. Start Toggle
2. Add a task "foo"
3. Stop foo
4. Add "reporting bugs"
5. Expect to see foo in waterfall.

### 📦 Additional info

![toggle-bug-report](https://user-images.githubusercontent.com/1176137/63653502-70651900-c722-11e9-9ded-2a3eb9f7b708.png)

**Comment by NghiaTranUIT** [comment]
@adamshostack Thank for the report. We have a question about it since I couldn't reproduce it as a new or old user.
1. When app launch at the first time, do you see the list and empty label? (see the screenshot)
<img width="452" alt="Screen Shot 2019-08-26 at 13 50 24" src="https://user-images.githubusercontent.com/5878421/63670986-9238cb80-c808-11e9-8900-b59d801c01cc.png">

I suppose that for some reason, the size of windows is collapse and set a minimal size, which is the size if Timer Bar.

If it happens, please try to resize the window, I suppose that we can see the list.
