### ISSUE TITLE
Time entries multiplied with different end times

### ISSUE THREAD

**Issue by SebastianKleineUsu** [toggl/toggldesktop#3397]
### 💻 Environment

Platform: 
OS Version: 
Toggl Version: 

### 🐞 Actual behavior
I had my notebook (win10) reinstalled this week and reinstalled Toggl. I have hillarious tracking times, coming from time entries being duplicated and having different end times. 
I've used the program as before.
Please also see attached screenshot.

### 💯 Expected behavior
Instead of having each entry duplicated with a wrong end time, it should exist only once with the correct end time.

### 🔨 Steps to reproduce
Sorry, but just used the software as ever before. Created new entries by typing in the field and using Start/stop or by using the "play -button" to create a new entry of an existing type.

### 📦 Additional info
![Toggl_error screenshot 20191004](https://user-images.githubusercontent.com/56157394/66203440-a6de6e00-e6a8-11e9-916f-d8f50dc33887.png)

**Comment by skel35** [comment]
Hi Sebastian!
The duplicate entries issue was caused by the 7.4.1022 version of the app.
Current version 7.4.1023 has this fixed and there will be no more entry duplication.

We're also looking into ways to remove duplicate entries.
My piece of advice here is to not edit the duplicate entries manually as it would be harder for us to detect that this is a duplicate. Otherwise, you can just manually delete the duplicated entries and continue working as normal with 7.4.1023 version of the desktop app or with the web app.

Sorry for the inconvenience this has caused you.

**Comment by andrewmurph** [comment]
I'm using the Mac app. This just happened to me! It was all fine, then in the last half hour I got a message saying my version of the app isn't supported. Hit TogglDesktop -> Check for update and let it update from 7.4.1022 to 7.4.1023 

After the update, it duplicated a handful of entries on Wednesday, Thursday, and today (Friday). Apparently I've tracked 66 hours today, 249 hours yesterday, and 55 hours on Wednesday!

I manually deleted them before noticing this bug report...
