### ISSUE TITLE
Toggl desktop adds a set of time entries with an incorrect end time (the time of last sync?) on sync

### ISSUE THREAD

**Issue by may1066** [toggl/toggldesktop#3399]
### 💻 Environment

Platform:  Windows 
OS Version:  Windows 10 version 1803
Toggl Version:  7.4.1023 

### 🐞 Actual behavior

When toggl desktop synced (after a day or so of refusing to connect and me reinstalling it) it seems to have created a set of time entries, for each start time and set the same end time of 2:21. Rendering the time spent on all my projects huge (249 hours of work yesterday!) and meaningless. [EDIT: I orginally thought it was reversing the start and end times but it seems to be adding in extra ones]

### 💯 Expected behavior

I expected a couple of missing time entries to sync and the rest (which were previously correctly stored) not to change. 

### 🔨 Steps to reproduce

I'm not sure, it was the latest version of toggl desktop I reinstalled it a couple of days ago because it was having trouble connecting and this morning it said the version was out of date so I downloaded the installer again and installed the new version. 
1. Set up a mix of entries, some run via the browser, some run via the desktop app, some started in one and ended in the other. 
2. Uninstall Toggl Desktop and reinstall from the latest installer
3. Allow to sync
4. Check time entries. 

### 📦 Additional info

[toggldesktop.log](https://github.com/toggl/toggldesktop/files/3690755/toggldesktop.log)

**Comment by skel35** [comment]
Hi!
The added entries issue was caused by the 7.4.1022 version of the app.
Current version 7.4.1023 has this fixed and there will be no more entry duplication.
I understand that it looked like the newest version created those duplicates as they appeared after you opened the new version.

We've already started deleting those added entries and you'll receive an e-mail when we delete yours just so you can make sure we haven't deleted any of your personal data.
Your options now are either 1. delete those entries manually or 2. not edit these entries for now as , otherwise, it might be harder for us to detect that the entry is one of those mistakenly created by us and delete it.

You can continue working normally with 7.4.1023 version of the desktop app or with the web app now, we can assure no new clones of entries will be added.

If you're interested in what's actually happened, here's brief information about the incident https://blog.toggl.com/toggl-desktop-issue-october-2019/
Apologies for the inconvenience this has caused you, both for issues with connection and for added entries.

**Comment by IndrekV** [comment]
Just to give more info. We have solid backups of all time entries so if it happens that something that didn't need to be deleted is deleted we can restore everything.

**Comment by may1066** [comment]
Ah, that makes sense, sorry for the confusion on my part! Thank you
